[build]
  base = "/"
  publish = "/dist"
  command = "jekyll build"

[[redirects]]
  from = "/api/resource"
  to = "https://px82vf9n78.execute-api.us-east-1.amazonaws.com/v1/resource"
  status = 301
  query = {file = ":file"}